name: remote ssh command
######### main branch에 push 되었을때만 실행#########
on: 
  push:            
    branches:
      - main
######### main branch에 push 되었을때만 실행#########
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: whoami